model:
  type: graphbp
  encoder:
    node_feat_dim: 256
    num_layers: 6

  embedder:
    emb_dim: 256 #emb_dim should equal to node_feat_dim
    num_layers: 6
    num_radial: 6
    num_spherical: 7
    num_basis: 32
    dist:
      type: power
    angle:
      type: spherical
  
data:
  train: !include ../common/ar_data_train_graphbp.yml
  collate_fn:
    type: graphbp
    

train:
  loss_weights:
    node: 1.0
    dist: 1.0
    angle: 1.0
    torsion: 1.0
    focus: 1.0
    contact: 1.0

  max_iters: 500000
  report_freq: 100
  batch_size: 16
  seed: 2022
  max_grad_norm: 100.0
  optimizer:
    type: adam
    lr: 1.e-5
    weight_decay: 0.000001
    beta1: 0.99
    beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.6
    patience: 100
    min_lr: 1.e-5 

eval:
  val_freq: 1000
