name: pl_decomp
version: sidechain
raw_path: ../datasets/crossdocked_v1.1_rmsd1.0_pocket10
split_path: ./data/split_by_name_10m.pt
transform:
  - type: choose_ctx_gen
  - type: featurize_protein_fa
  - type: featurize_ligand_ar
    mode: basic
  - type: reindex_atom_seq_graph

  

