model:
  type: difffg
  checkpoint: ./logs/denovo/d3fg_fg/d3fg_fg_2024_05_05__20_05_36/checkpoints/951000.pt

data:
  test: 
    name: pl_fg
    raw_path: ./data/case_study
    split_path: ./data/case_study/split_by_name.pt
    processed_dir: ./data/case_study/processed/
    transform:
      - type: select_fg
      - type: remove_ligand
      - type: featurize_protein_fg
        mode: fg_only
      - type: center_frame_pos
        center_flag: protein

      - type: assign_fgnum
        distribution: prior_distcond
      - type: assign_fgtype
        distribution: uniform
        mode: fg_only
      - type: assign_fgpos
        distribution: gaussian
      - type: assign_fgori
        distribution: uniform
      - type: merge
        keys: 
          - protein
          - ligand

  follow_batch: 
    - protein_type_fg
    - ligand_type_fg
    

sampling:
  seed: 2022
  num_samples: 500
  translate: false

fg2mol:
  basic_mode: true
