name: pl_fa
raw_path: ./raw_data/crossdocked_v1.1_rmsd1.0_pocket10
split_path: ./data/split_by_name_10m.pt
transform:
  - type: featurize_protein_fa
  - type: featurize_ligand_fa
  - type: center_pos
    center_flag: protein
  - type: merge
    keys:
      - protein
      - ligand
